[package]

name = "quick-csv_count"
version = "0.0.1"
authors = [ "Your name <you@example.com>" ]

[[bin]]
name = "quick-count"

[dependencies]
quick-csv = "0.1"

[profile.release]
opt-level = 3
lto = true
