[package]
name = "csvreader"
version = "0.0.1"
authors = [ "Ewan Higgs <ewan_higgs@yahoo.co.uk>" ]

[[bin]]
name = "csvreader"

[dependencies]
libc = "0.2"
num-traits = "0.1"

[profile.release]
opt-level = 3
lto = true
