#!/bin/bash

# run 'mvn install' to install the project locally and then use this csv:
# ./OpenCsv

bindir=$(dirname $0)
csv_path=$bindir/target/csv-1.0-SNAPSHOT-jar-with-dependencies.jar
java -cp "${csv_path}" csv.OpenCsvCount 5 /tmp/count.csv
